# Tap
tap "mongodb/brew" # https://github.com/mongodb/homebrew-brew
brew "mongodb/brew/mongodb-community@7.0"

# Development
brew "openjdk" # https://openjdk.java.net/
brew "docker" # https://www.docker.com/
brew "docker-compose" # https://docs.docker.com/compose/
brew "pyenv" # https://github.com/pyenv/pyenv
brew "yarn" # https://yarnpkg.com/
cask "android-studio"  # https://developer.android.com/studio/
cask "visual-studio-code" # https://code.visualstudio.com/
cask "google-cloud-sdk" # https://cloud.google.com/sdk/
cask "postman" # https://www.postman.com/

# Media & documents
brew "ffmpeg" # https://ffmpeg.org/
brew "imagemagick" # https://imagemagick.org/
brew "ghostscript" # ImageMagick depends on Ghostscript fonts - https://imagemagick.org/script/download.php
brew "pandoc" # https://pandoc.org/
cask "basictex" # for Pandoc - https://www.tug.org/mactex/morepackages.html
brew "rsync" # https://rsync.samba.org/ - GNU rsync; macOS ships openrsync, which lacks --info=progress2 and some filter rules
#cask "vlc" # From another source for me atm - https://www.videolan.org/vlc/

# Command-line utils
# GNU utilities (installed with 'g' prefix: gsed, gtar, etc.)
# To use without prefix: export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
brew "coreutils"
brew "gnu-sed"
brew "gnu-tar"
brew "fd" # https://github.com/sharkdp/fd
brew "htop" # https://htop.dev/
brew "jo" # https://github.com/jpmens/jo
brew "jq" # https://stedolan.github.io/jq/
brew "mkcert" # https://github.com/FiloSottile/mkcert
brew "pstree" # http://www.thp.uni-duisburg.de/pstree/
brew "pv" # https://www.ivarch.com/programs/pv.shtml
brew "rename" # http://plasmasturm.org/code/rename
brew "terminal-notifier" # https://github.com/julienXX/terminal-notifier
brew "tree" # http://mama.indstate.edu/users/ice/tree/
brew "hyperfine" # "https://github.com/sharkdp/hyperfine"

# Screensavers
cask "aerial" # https://github.com/JohnCoates/Aerial
cask "brooklyn" # https://github.com/pedrommcarrasco/Brooklyn
cask "developerexcuses" # https://github.com/kimar/DeveloperExcuses

# Fonts - https://github.com/Homebrew/homebrew-cask-fonts
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font" # my preference for Visual Studio Code

# Apps
cask "iterm2" # https://iterm2.com/ - shell integration set up in dotfiles-setup/shell-tools.zsh
cask "appcleaner" # https://freemacsoft.net/appcleaner/
cask "google-chrome"  # https://www.google.com/chrome/
cask "firefox"  # https://www.mozilla.org/firefox/
cask "spotify"  # https://www.spotify.com/
cask "suspicious-package" # https://www.mothersruin.com/software/SuspiciousPackage/
cask "skitch" # https://evernote.com/products/skitch

# Other
brew "mas"  # https://github.com/mas-cli/mas

# Virtualization
#cask "virtualbox"  # https://www.virtualbox.org/
#cask "virtualbox-extension-pack" # https://www.virtualbox.org/
#cask "docker" # https://www.docker.com/products/docker-desktop

# App Store apps (via mas)
mas "Bitwarden", id: 1352778147
mas "CopyClip", id: 595191960
mas "Xcode", id: 497799835
